<?php

namespace MigrationBundle\Repository;

/**
 * WpTermTaxonomyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WpTermTaxonomyRepository extends \Doctrine\ORM\EntityRepository
{
}
