<?php

namespace LaFolleAgenceBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends EntityRepository
{

    public function getComments() {
        $comments = $this->createQueryBuilder('u')
                             ->orderBy('u.id', 'DESC')
                             ->getQuery();
        return $comments->getResult();
    }
}
