<?php

namespace LaFolleAgenceBundle\Repository;

/**
 * LinkImageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LinkImageRepository extends \Doctrine\ORM\EntityRepository
{
}
