<?php

namespace LaFolleAgenceBundle\Repository;

use LaFolleAgenceBundle\Entity\Category;
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends EntityRepository
{
    const MAX_RESULT = 4;
    /**
     * @param int $page
     * @param int $itemPerPage
     * @return Paginator
     */
    public function getByPage($page, $itemPerPage = self::MAX_RESULT)
    {
        if ($page > 0) {
            $offset = ($page - 1) * $itemPerPage;
        } else {
            $offset = 0;
        }
        $query = $this->createQueryBuilder('p')
            ->orderBy('p.publicationDate', 'DESC')
            ->where('p.statut = 1')
            ->setFirstResult($offset)
            ->setMaxResults($itemPerPage)
            ;
        return new Paginator($query);
    }

    /**
     * @param $category
     * @param $page
     * @param int $itemPerPage
     * @return Paginator
     */
    public function categoryGetByPage(Category $category, $page, $itemPerPage = self::MAX_RESULT)
    {
        if ($page > 0) {
            $offset = ($page - 1) * $itemPerPage;
        } else {
            $offset = 0;
        }
        $query = $this->createQueryBuilder('p')
            ->innerJoin('p.categorys', 'c')
            ->where('c.id = ?1')
            ->orderBy('p.publicationDate', 'DESC')
            ->setParameter(1, $category->getId())
            ->andWhere('p.statut = 1')
            ->setFirstResult($offset)
            ->setMaxResults($itemPerPage)
        ;
        return new Paginator($query);
    }

    /**
     * @param $limit
     * @return array
     */
    public function getLastSixArticles ($limit) {
        $carouselArticles = $this->createQueryBuilder('la')
            ->orderBy('la.id', 'DESC')
            ->where('la.statut = 1')
            ->setMaxResults($limit)
            ->getQuery();
        return $carouselArticles->getResult();
    }

    /**
     * @return Paginator
     */
    public function getAllOrderByDate()
    {
        $query = $this->createQueryBuilder('p')
            ->orderBy('p.publicationDate', 'DESC')
            ->where('p.statut = 1');

        return new Paginator($query);
    }

    /**
     * @return array
     */
    public function getComments() {
        $comments = $this->createQueryBuilder('co')
            ->orderBy('co.id', 'DESC')
            ->getQuery();
        return $comments->getResult();

    }
}
